[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  VITE_BASE_URL = "https://backend-cabsy.onrender.com"
